# Generated by Django 3.2.9 on 2021-11-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "tagType",
                    models.TextField(
                        choices=[
                            ("SH", "sheet"),
                            ("CO", "composer"),
                            ("AR", "arranger"),
                            ("GE", "genre"),
                            ("KE", "key"),
                            ("TI", "time"),
                            ("TE", "tempo"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("dateAdded", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(null=True)),
                ("tags", models.ManyToManyField(to="api.Tag")),
            ],
        ),
    ]
