# Generated by Django 3.2.9 on 2021-11-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
