# Generated by Django 3.2.9 on 2021-11-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_concert_note_performance_performer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performance",
            name="request",
            field=models.BooleanField(default=False),
        ),
    ]
