# Generated by Django 3.2.9 on 2021-11-27 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_performance_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="concert",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="api.concert"
            ),
            preserve_default=False,
        ),
    ]
