# Generated by Django 3.2.9 on 2021-11-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_note_concert"),
    ]

    operations = [
        migrations.AddField(
            model_name="performance",
            name="index",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="note",
            name="public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="performance",
            constraint=models.UniqueConstraint(
                fields=("id", "index"), name="unique_concert_index"
            ),
        ),
    ]
